services:
    mariadb:
      image: mariadb:11.4
      expose:
        - "3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      healthcheck:
        test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su=root", "--connect", "--innodb_initialized" ]
        retries: 5

    redis:
      image: redis:8
      expose:
        - "6379"
      healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        retries: 5

    grimoirelab_core:
      restart: on-failure:3
      image: grimoirelab/grimoirelab:2.x
      environment:
        GRIMOIRELAB_DB_HOST: mariadb
        GRIMOIRELAB_DB_PORT: 3306
        GRIMOIRELAB_DB_DATABASE: core_db
        GRIMOIRELAB_DB_USER: root
        GRIMOIRELAB_DB_PASSWORD: ""
        GRIMOIRELAB_REDIS_HOST: redis
        GRIMOIRELAB_REDIS_PORT: 6379
        GRIMOIRELAB_REDIS_PASSWORD: ""
      expose:
        - "9314"
      volumes:
        - core-static:/core_static/
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
      command: grimoirelab run server

    grimoirelab_core_eventizers:
      restart: on-failure:3
      image: grimoirelab/grimoirelab:2.x
      environment:
        GRIMOIRELAB_DB_HOST: mariadb
        GRIMOIRELAB_DB_PORT: 3306
        GRIMOIRELAB_DB_DATABASE: core_db
        GRIMOIRELAB_DB_USER: root
        GRIMOIRELAB_DB_PASSWORD: ""
        GRIMOIRELAB_REDIS_HOST: redis
        GRIMOIRELAB_REDIS_PORT: 6379
        GRIMOIRELAB_REDIS_PASSWORD: ""
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
      command: grimoirelab run eventizers

    grimoirelab_core_archivists:
      restart: on-failure:3
      image: grimoirelab/grimoirelab:2.x
      environment:
        GRIMOIRELAB_DB_HOST: mariadb
        GRIMOIRELAB_DB_PORT: 3306
        GRIMOIRELAB_DB_DATABASE: core_db
        GRIMOIRELAB_DB_USER: root
        GRIMOIRELAB_DB_PASSWORD: ""
        GRIMOIRELAB_REDIS_HOST: redis
        GRIMOIRELAB_REDIS_PORT: 6379
        GRIMOIRELAB_REDIS_PASSWORD: ""
        GRIMOIRELAB_ARCHIVIST_STORAGE_URL: "https://opensearch-node1:9200"
        GRIMOIRELAB_ARCHIVIST_STORAGE_USERNAME: "admin"
        GRIMOIRELAB_ARCHIVIST_STORAGE_PASSWORD: "Admin-Password-1234"
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
        opensearch-node1:
          condition: service_started
      command: grimoirelab run archivists

    sortinghat:
      restart: on-failure:3
      image: grimoirelab/sortinghat
      environment:
        - SORTINGHAT_SECRET_KEY=secret
        - SORTINGHAT_DB_HOST=mariadb
        - SORTINGHAT_DB_PORT=3306
        - SORTINGHAT_DB_DATABASE=sortinghat_db
        - SORTINGHAT_DB_USER=root
        - SORTINGHAT_DB_PASSWORD=
        - SORTINGHAT_REDIS_HOST=redis
        - SORTINGHAT_REDIS_PASSWORD=
        - SORTINGHAT_SUPERUSER_USERNAME=admin
        - SORTINGHAT_SUPERUSER_PASSWORD=admin
        - SORTINGHAT_ALLOWED_HOST=sortinghat,nginx,localhost,127.0.0.1,[::1]
        - SORTINGHAT_CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      expose:
        - "9314"
      volumes:
        - sortinghat-static:/opt/venv/lib/python3.12/site-packages/sortinghat/static/
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy

    sortinghat_worker:
      image: grimoirelab/sortinghat-worker
      environment:
        - SORTINGHAT_SECRET_KEY=secret
        - SORTINGHAT_DB_HOST=mariadb
        - SORTINGHAT_DB_PORT=3306
        - SORTINGHAT_DB_DATABASE=sortinghat_db
        - SORTINGHAT_DB_USER=root
        - SORTINGHAT_DB_PASSWORD=
        - SORTINGHAT_REDIS_HOST=redis
        - SORTINGHAT_REDIS_PASSWORD=
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy

    opensearch-node1:
      image: opensearchproject/opensearch:2.19.3
      environment:
        - cluster.name=opensearch-cluster
        - node.name=opensearch-node1
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
        - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin-Password-1234
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - 9200:9200
        - 9600:9600

    opensearch-dashboards:
      image: opensearchproject/opensearch-dashboards:2.19.3
      ports:
        - 5601:5601
      expose:
        - "5601"
      environment:
        OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'

    nginx:
      restart: on-failure:3
      image: nginx:latest
      volumes:
        - ../default-grimoirelab-settings/nginx.conf.template:/etc/nginx/templates/default.conf.template
        - ../default-grimoirelab-settings/uwsgi_params:/etc/nginx/uwsgi_params
        - sortinghat-static:/sortinghat:ro
        - core-static:/grimoirelab_core:ro
      ports:
        - 8000:8000
      depends_on:
        - sortinghat
        - grimoirelab_core
      healthcheck:
        test: "curl -s --head http://localhost:8000/identities/api/ | grep Set-Cookie || exit 1"
        retries: 5

volumes:
  sortinghat-static:
  core-static:
